Gamma optimizations and benchmarks
probcomp/Gen.clj pull request #69
Opened 2024-04-16 22:12 UTC by eightysteele

Turns out that pre-computing constants and type-hinting functions has a big performance gain:

- `(gamma 2.5)` 77.40% speedup (execution mean 4.889986 µs → 1.104972 µs)
- `(log-gamma 10)` 63.92% speedup (execution mean 4.845715 µs → 1.748155 µs)
- `(log-gamma-1p -0.05)` 76.86% speedup (execution mean 4.981068 µs → 1.152443 µs)
- `(inv-gamma-1pm1 -0.05)` 77.85% speedup (execution mean 4.582663 µs → 1.015241 µs)
- `(lanczos-approximation 170)` 73.15% speedup (execution 4.276010 µs → 1.148002 µs)

Did this for `math.gamma` and `math.utils`. Also experimenting with a way to define and run benchmarks like tests: Benchmarks are defined in the `/benchmark` directory, then functions to benchmark are tagged with `^:benchmark` and profiled with Criterium. Just run `bb benchmark:clj` to compute benchmarks! See `gamma_benchmark.cljc` for an example.

2024-04-18 16:14 UTC, sritchie requested changes

2024-04-18 16:14 UTC, sritchie commented on benchmark/benchmark_runner.cljc
> +(defn run-benchmarks
I think you can do this with our normal test runner, without adding this whole namespace... https://github.com/cognitect-labs/test-runner see the include and exclude options: https://github.com/cognitect-labs/test-runner?tab=readme-ov-file#invoke-with-clojure--m-clojuremain

2024-04-18 16:14 UTC, sritchie commented on benchmark/gen/distribution/math/gamma_benchmark.cljc
> +(defn ^:benchmark lanczos-approximation-computation-time
you should be able to use `deftest` and then the test selectors I mentioned above

2024-04-18 16:14 UTC, sritchie commented on benchmark/gen/distribution/math/gamma_benchmark.cljc
> +    (mapv f x)))
for side effects, use `run!` instead of `mapv`

2024-04-18 16:14 UTC, sritchie commented on src/gen/distribution/math/utils.cljc
> +(def ^:no-doc ^:const sqrt-2pi
wild, I have some annotations I need to add in Emmy!

2024-04-19 19:10 UTC, eightysteele commented on benchmark/benchmark_runner.cljc
> +(defn run-benchmarks
Yeah, good call. I swapped in test runner—much better.

2024-04-19 19:10 UTC, eightysteele commented on benchmark/gen/distribution/math/gamma_benchmark.cljc
> +    (mapv f x)))
Nice, done.

2024-04-19 19:11 UTC, eightysteele commented on src/gen/distribution/math/utils.cljc
> +(def ^:no-doc ^:const sqrt-2pi
So good!

2024-04-19 19:11 UTC, eightysteele commented
@sritchie I addressed the comments and benchmark now ride on test runner, boom. 

I'm assuming that when a benchmark test runs, we want it to fail if it diverged within some threshold of a baseline. To define a baseline, it seems reasonable to have something like this:

```clojure
(def ^:no-doc ^:const lanczos-approximation-baseline
  [{:n 15
    :x 9
    :mean 3.127368933269932E-6
    :variance 1.5780434242573877E-14
    :lower-q 2.984515105404977E-6
    :upper-q 3.320172412426692E-6}
   {:n 15
    :x 100
    :mean 2.0160584455226908E-7
    :variance 7.928671640576774E-18
    :lower-q 1.9907849968797706E-7
    :upper-q 2.0489675953499433E-7}
   {:n 15
    :x 170
    :mean 2.040524636004644E-7
    :variance 5.795520133553684E-18
    :lower-q 2.0120967339244923E-7
    :upper-q 2.0719692107157572E-7}])
```

and then the actual benchmark test just maps over entries in the baseline and runs `crit/quick-benchmark`, like so:

```clojure
(deftest ^:benchmark lanczos-approximation-benchmark
  []
  (let [f (fn[b]
            (let [n (:n b)
                  x (:x b)
                  mean (:mean b)
                  variance (:variance b)
                  lower-q (:lower-q b)
                  upper-q (:upper-q b)
                  stats (crit/quick-benchmark
                         (dotimes [_ n]
                           (g/lanczos-approximation x)) {})]
              (testing "against lanczos approximation baseline"
                (with-comparator (within 1e-3)
                  (is (ish? mean (first (:mean stats))) x)
                  (is (ish? variance (first (:variance stats))) x)
                  (is (ish? lower-q (first (:lower-q stats))) x)
                  (is (ish? upper-q (first (:upper-q stats))) x)))))]
    (run! f lanczos-approximation-baseline)))
    ```
    
    This is implemented right now, so you can run `bb benchmark:clj` to see it work.

2024-05-14 18:22 UTC, sritchie commented on benchmark/gen/distribution/math/gamma_benchmark.cljc
> +            (crit/quick-bench
bummer that criterium can't take a label!

2024-05-14 18:23 UTC, sritchie commented on deps.edn
> +   :exec-args {:includes [:benchmark] :dirs ["benchmark"] :patterns [".*-benchmark$"]}
okay I see here that we specify the test name pattern... but what does the metadata do?

2024-05-14 18:23 UTC, sritchie approved these changes
one comment...

2024-05-14 19:01 UTC, eightysteele commented on deps.edn
> +   :exec-args {:includes [:benchmark] :dirs ["benchmark"] :patterns [".*-benchmark$"]}
yeah good q! so from test-runner, `:patterns` is for the test filenames to run and `:includes` is the collection of test metadata keywords to include. so, this says "find all files with a name that ends with "benchmark" and in those files run any function with the `:benchmark` metadata.

2024-05-14 19:07 UTC, eightysteele commented
@sritchie yep, i responded—lmk if that explanation about `:benchmark` metadata makes sense!

2024-06-01 02:05 UTC, merged

2024-06-01 03:35 UTC, eightysteele commented
💥